utils.git: Make reverse_blame() handle non-UTF8 output
Because for _parse_blame_porcelain() to handle bytes input it would have
to be modified, use fallback 8-bit encoding instead ('latin1').

Explanation: the regexp and the `sep` parameter in split() would need
to be bytes, otherwise it throws the following exception (for regexp):

  File "src/utils/git.py", line 134, in _parse_blame_porcelain
    if match := _parse_blame_porcelain.regexp.match(line):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: cannot use a string pattern on a bytes-like object