test_utils_git.py: Use `expected, actual` in self.assert*Equal()
Arguments of unittest.TestCase.assertEqual() and .assertCountEqual()
are named 'first' and 'second', but when the assertion fails, they are
described by PyCharm test runner as "Expected" and "Actual":

  second != first

  Expected :first
  Actual   :second
  <Click to see difference>

Change the order of `expected` and `actual` variables passed as
parameters to match this convention.

The AssertionError exception do not mention which is expected and which
is actual:

      self.assertEqual("first", "second")
  AssertionError: 'first' != 'second'
  - first
  + second