utils.git: Make unidiff() handle non-UTF8 output
If diff output cannot be decoded with the 'utf-8' codec (default file
encoding), then decode it with 'latin1' (fallback encoding), because
unidiff can only handle strings.

With bytes unidiff.PatchSet fails with the following error message:

  File "[...]/site-packages/unidiff/patch.py", line 483, in _parse
    is_diff_git_header = RE_DIFF_GIT_HEADER.match(line) or \
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: expected string or bytes-like object, got 'int'